# to upload
# git tag v1.0.0
# git push origin v1.0.0
name: Build and Upload Apptainer Image

on:
  push:
    tags:
      - 'v*.*.*'  # Matches tags like v1.2.3

jobs:
  build-apptainer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Build Apptainer image
        run: |
          apptainer build seapodym-parallel-gnu.sif apptainer/seapodym-parallel-gnu.def

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: apptainer-image
          path: seapodym-parallel-gnu.sif
