---
name: Build and test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: mpi4py/setup-mpi@v1
      - uses: ssciwr/doxygen-install@v1
      - name: Download ADMB
        run: "wget https://github.com/admb-project/admb/releases/download/admb-13.2/admb-13.2-linux.zip"
      - name: Extract ADMB
        run: "unzip admb-13.2-linux.zip"
      - run: mv admb ~/
      - run: pwd
      - run: ls -l
      - run: mkdir build
      - name: Configure with cmake
        run: cmake -B build -DADMB_HOME=~/admb .
      - name: Build with cmake
        run: cmake --build build --target doc_doxygen
      - name: Test with cmake
        run: ctest
      - run: ls -l docs
      - run: ls -l build

