name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gfortran g++ cmake make openmpi-bin libopenmpi-dev

    - name: Build ADMB
      run: |
        git clone https://github.com/admb-project/admb.git
        cd admb
        git checkout v2.2.1
        ./configure --prefix=/usr/local
        make
        make install

    - name: Configure project
      run: cmake -S . -B build -DADMB_HOME=/usr/local/

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build || true
